name: DarkRP
version: ${project.version}
main: darkrp.DarkRP
authors: [ CoronaCreeper ]
description: Plugin na RP dla DarkRP
commands:
  med:
  discord:
  rp:
  regulamin:
  onAdmin:
  offAdmin:
  plecak:
  invsee:
  stworzdowod:
  pay:
  wizytowka:
  buy:
  ulecz:
    permission: rp.lekarz.leczenie